# Common configuration for all Proxmox nodes
zabbix_agent2_config:
  server: "{{ zabbix_server_ip }}"
  serveractive: "{{ zabbix_server_ip }}"
  hostname: "{{ inventory_hostname }}.{{ domain }}"
  timeout: 30
  logfilesize: 100

# NUT UPS configuration
nut_mode: netclient
nut_server: eagle.bustinjailey.org
nut_ups_name: apc2200

# NUT passwords (should be overridden in vault.yml)
nut_upsmon_password: "{{ vault_nut_upsmon_password | default('CHANGE_ME') }}"

# DNS configuration
dns_search: bustinjailey.org
dns_servers:
  - 192.168.1.187
  - 192.168.1.254

# Update configuration
update_reboot_timeout: 600
