---
- name: restart nut
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  loop: "{{ nut_services_to_restart }}"
  vars:
    nut_services_to_restart: >-
      {{
        (['nut-server', 'nut-monitor'] if (ups_connected | default(false)) else ['nut-monitor'])
      }}
  ignore_errors: yes
