---
- name: Download Zabbix repository configuration
  get_url:
    url: "https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian12_all.deb"
    dest: /tmp/zabbix-release.deb
    mode: "0644"

- name: Install Zabbix repository
  apt:
    deb: /tmp/zabbix-release.deb
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Zabbix agent 2
  apt:
    name: zabbix-agent2
    state: present

- name: Configure Zabbix agent 2
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart zabbix-agent2

- name: Ensure Zabbix agent 2 is running and enabled
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes
    daemon_reload: yes
