---
- name: Add Zabbix repository key
  apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Add Zabbix repository
  apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/6.0/debian {{ ansible_distribution_release }} main"
    state: present
    filename: zabbix
  notify: update apt cache

- name: Update apt cache
  apt:
    update_cache: yes
  when: not ansible_check_mode

- name: Install Zabbix agent 2
  apt:
    name: zabbix-agent2
    state: present

- name: Configure Zabbix agent 2
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify: restart zabbix-agent2

- name: Ensure Zabbix agent 2 is running and enabled
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes
    daemon_reload: yes

# NVIDIA GPU monitoring support
# Note: NVIDIA drivers are now managed by the dedicated nvidia-drivers role
- name: Install NVIDIA ML Python bindings for monitoring
  apt:
    name: python3-pynvml
    state: present
    update_cache: yes
  when: has_nvidia_gpu | default(false)

- name: Verify NVIDIA driver is available for monitoring
  shell: nvidia-smi --query-gpu=name --format=csv,noheader
  register: nvidia_gpu_detection
  failed_when: false
  changed_when: false
  when: has_nvidia_gpu | default(false)

- name: Display GPU detection results
  debug:
    msg: "Detected GPU: {{ nvidia_gpu_detection.stdout | default('No GPU detected') }}"
  when: has_nvidia_gpu | default(false)

- name: Warn if GPU expected but not detected
  debug:
    msg: "WARNING: NVIDIA GPU expected but not detected. Ensure nvidia-drivers role has been applied first."
  when:
    - has_nvidia_gpu | default(false)
    - nvidia_gpu_detection.rc != 0
