---
- name: Install NUT packages
  apt:
    name:
      - nut
      - nut-client
      - nut-server
    state: present
  notify: restart nut

- name: Flush handlers to ensure services are available
  meta: flush_handlers

- name: Configure NUT mode
  template:
    src: nut.conf.j2
    dest: /etc/nut/nut.conf
    owner: root
    group: nut
    mode: "0640"
  notify: restart nut

- name: Configure UPS definitions (server only)
  template:
    src: ups.conf.j2
    dest: /etc/nut/ups.conf
    owner: root
    group: nut
    mode: "0640"
  when: ups_connected | default(false)
  notify: restart nut

- name: Configure UPS daemon (server only)
  template:
    src: upsd.conf.j2
    dest: /etc/nut/upsd.conf
    owner: root
    group: nut
    mode: "0640"
  when: ups_connected | default(false)
  notify: restart nut

- name: Configure UPS users (server only)
  template:
    src: upsd.users.j2
    dest: /etc/nut/upsd.users
    owner: root
    group: nut
    mode: "0640"
  when: ups_connected | default(false)
  notify: restart nut

- name: Configure UPS monitor
  template:
    src: upsmon.conf.j2
    dest: /etc/nut/upsmon.conf
    owner: root
    group: nut
    mode: "0640"
  notify: restart nut

- name: Ensure NUT services are running
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nut-monitor
    - nut-server
  when: ups_connected | default(false)

- name: Check available NUT services
  shell: systemctl list-unit-files | grep -E '^nut-' | awk '{print $1}'
  register: available_nut_services
  changed_when: false
  when: not (ups_connected | default(false))

- name: Debug available NUT services
  debug:
    msg: "Available NUT services: {{ available_nut_services.stdout_lines }}"
  when: not (ups_connected | default(false))

- name: Ensure NUT client service is running (try nut-monitor first)
  systemd:
    name: nut-monitor
    state: started
    enabled: yes
  when:
    - not (ups_connected | default(false))
    - "'nut-monitor.service' in available_nut_services.stdout"
  retries: 3
  delay: 5

- name: Ensure NUT client service is running (fallback to nut-client)
  systemd:
    name: nut-client
    state: started
    enabled: yes
  when:
    - not (ups_connected | default(false))
    - "'nut-monitor.service' not in available_nut_services.stdout"
    - "'nut-client.service' in available_nut_services.stdout"
  retries: 3
  delay: 5
