---
- name: Download Proxmox VE post-install script
  get_url:
    url: https://raw.githubusercontent.com/tteck/Proxmox/main/misc/post-pve-install.sh
    dest: /tmp/post-pve-install.sh
    mode: "0755"

- name: Run post-install script headless
  shell: |
    export TERM=linux
    cat << EOF | bash /tmp/post-pve-install.sh
    y
    y
    y
    y
    y
    y
    n
    y
    y
    EOF
  # Input sequence:
  # y - Start the Proxmox VE Post Install Script
  # y - Correct Proxmox VE sources
  # y - Disable pve-enterprise repository
  # y - Enable pve-no-subscription repository
  # y - Correct ceph package sources
  # y - Add pvetest repository
  # n - Do NOT disable high availability (preserve HA functionality)
  # y - Disable subscription nag (remove annoying popup)
  # y - Update Proxmox VE now (install latest updates immediately)
  args:
    creates: /etc/apt/sources.list.d/pve-no-subscription.list
  environment:
    TERM: linux
    DEBIAN_FRONTEND: noninteractive
  register: post_install_result
  failed_when: post_install_result.rc != 0

- name: Show post-install script output
  debug:
    msg: "{{ post_install_result.stdout_lines }}"
  when: post_install_result is defined and post_install_result.changed
