---
# Handlers for NVIDIA driver installation and configuration
# Updated for official network repository installation method

- name: update apt cache
  apt:
    update_cache: yes

- name: reboot system
  reboot:
    reboot_timeout: "{{ installation_config.reboot_timeout | default(600) }}"
    connect_timeout: 20
    test_command: uptime
    msg: "Rebooting system after NVIDIA driver installation"
  when: not ansible_check_mode

- name: wait for system
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enable nvidia devices service
  systemd:
    name: nvidia-devices
    enabled: yes
    state: started
    daemon_reload: yes

- name: enable nvidia persistence
  systemd:
    name: nvidia-persistenced
    enabled: yes
    state: started
    daemon_reload: yes

- name: update ldconfig
  shell: ldconfig
  changed_when: false

- name: load nvidia modules
  shell: modprobe {{ item }}
  loop: "{{ nvidia_modules }}"
  failed_when: false
  changed_when: false

- name: restart nvidia services
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  loop:
    - nvidia-devices
    - nvidia-persistenced
  failed_when: false

- name: create nvidia device nodes
  shell: /usr/local/bin/create-nvidia-devices.sh
  changed_when: false
  failed_when: false

- name: verify nvidia installation
  shell: nvidia-smi
  register: nvidia_verification
  changed_when: false
  failed_when: false
  retries: 3
  delay: 10

- name: display nvidia verification
  debug:
    var: nvidia_verification.stdout_lines
  when: nvidia_verification.stdout_lines is defined

- name: cleanup temp files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/cuda-keyring.deb
    - /tmp/nvidia-installer.log
  failed_when: false