---
- name: Install Python dependencies
  apt:
    name:
      - python3
      - python3-apt
      - python3-pip
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Configure DNS resolution
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: Ensure system is up to date
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
