all:
  children:
    proxmox_cluster:
      hosts:
        eagle:
          ansible_host: eagle.bustinjailey.org
          ups_connected: true
        proxmox:
          ansible_host: proxmox.bustinjailey.org
        fractal:
          ansible_host: fractal.bustinjailey.org
        dell:
          ansible_host: dell.bustinjailey.org
      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        zabbix_server_ip: 192.168.1.193
        dns_server: 192.168.1.187
        domain: bustinjailey.org

