all:
  children:
    proxmox_cluster:
      hosts:
        eagle:
          ansible_host: eagle.bustinjailey.org
          ups_connected: true
          backup_interface_fallback: "enp9s0f0np0"
          backup_node: true
          backup_file_paths:
            - "/storage/backup"
        proxmox:
          ansible_host: proxmox.bustinjailey.org
          backup_interface_fallback: "eno1"
          backup_node: true
          backup_file_paths: []
        fractal:
          ansible_host: fractal.bustinjailey.org
        dell:
          ansible_host: dell.bustinjailey.org
          has_nvidia_gpu: true
          nvidia_gpu_model: "Quadro T2000"
      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        zabbix_server_ip: 192.168.1.193
        dns_server: 192.168.1.187
        domain: bustinjailey.org

