---
- name: Configure new Proxmox cluster node
  hosts: proxmox_cluster
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Display configuration start message
      debug:
        msg: "Starting configuration of Proxmox cluster node: {{ inventory_hostname }}"

  roles:
    - role: common
      tags: ["common", "base"]
    - role: nvidia-drivers
      tags: ["nvidia", "gpu", "cuda"]
      when: has_nvidia_gpu | default(false)
    - role: zabbix-agent
      tags: ["monitoring", "zabbix"]
      when: enable_zabbix_monitoring | default(true)
    - role: nut-ups
      tags: ["ups", "power"]
      when: enable_nut_ups | default(false)

  post_tasks:
    - name: Display configuration completion message
      debug:
        msg: "Proxmox cluster node configuration completed for: {{ inventory_hostname }}"
