---
- name: Update Proxmox cluster
  hosts: proxmox_cluster
  gather_facts: yes
  serial: 1 # Update one node at a time
  tasks:
    - name: Update Proxmox packages
      block:
        - name: Update package cache
          apt:
            update_cache: yes

        - name: Upgrade all packages
          apt:
            upgrade: dist
            autoremove: yes
            autoclean: yes
          register: apt_upgrade_result

        - name: Check if reboot is required
          stat:
            path: /var/run/reboot-required
          register: reboot_required

        - name: Reboot if required
          reboot:
            reboot_timeout: "{{ update_reboot_timeout }}"
          when: reboot_required.stat.exists
      rescue:
        - name: Log update failure
          debug:
            msg: "Failed to update {{ inventory_hostname }}: {{ ansible_failed_result.msg }}"

    - name: Get list of containers
      shell: |
        pct list | tail -n +2 | awk '{print $1}'
      register: lxc_list
      changed_when: false

    - name: Update LXC containers
      include_tasks: update-lxc.yml
      loop: "{{ lxc_list.stdout_lines }}"
      loop_control:
        loop_var: lxc_id

    - name: Get list of VMs
      shell: |
        qm list | tail -n +2 | awk '{print $1}'
      register: vm_list
      changed_when: false

    - name: Update VMs (if running and agent enabled)
      include_tasks: update-vm.yml
      loop: "{{ vm_list.stdout_lines }}"
      loop_control:
        loop_var: vm_id
